### ISSUE TITLE
Clock Options

### ISSUE THREAD

**Issue by Jo3yDaPh1sH** [arthur-liberman/service.openvfd#3]
Any Chance of adding a 12 hour option? I have 12 hr set in kodi and it displays correctly, but the VFD still uses 24hr format.

**Comment by arthur-liberman** [comment]
Sure, I'm working on it.

**Comment by arthur-liberman** [comment]
@Jo3yDaPh1sH 
Option added, but since the clock is displayed using the driver [linux_openvfd](https://github.com/arthur-liberman/linux_openvfd), you will need to edit your vfd.conf file to make it work.
At the end of the vfd.conf file, add the following: `clock_12h_format='1'` (**remove** the line or comment it out to disable option) and reboot.

It will be available starting with the next nightly build.

**Comment by Jo3yDaPh1sH** [comment]
That's great! Thanks for all your hard work!
